config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, skip: [:passwords, :confirmations, :unlocks]
  
  root "menu#index"

  get "/menu", to: "menu#index"
  get "/clientes", to: "clientes#index"
  post "/clientes", to: "clientes#create"
  get "/clientes/new", to: "clientes#new", as: :new_cliente
  get "/clientes/:id", to: "clientes#details", as: :cliente
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :mascota, class_name: "Mascota", foreign_key: "cliente_id"
end

app/models/mascota.rb
class Mascota < ApplicationRecord
    belongs_to :cliente, class_name: "Cliente", foreign_key: "cliente_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname, :nickname])
    end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @clientes = Cliente.all
    end

    def details
        @cliente = Cliente.find(params[:id])
    end

    def new
        @nuevo = Cliente.new # Crea un objeto vacío
    end
    
    def create
      @nuevo = Cliente.new(cliente_params)
        if @nuevo.save
            redirect_to clientes_path
        else
            render :new
        end        
    end
    
    private

    def cliente_params
        params.require(:cliente).permit(:nombre, :direccion, :email, :telefono)
        # :cliente busca el objeto en el post y lo retorna
        # .permit() define los campos que se pueden modificar o llamar para mandar a la base de datos
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @user = current_user
    end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/clientes/details.html.erb
<div>
    <th>
        <td><%= @cliente.id %></td>
        <td><%= @cliente.nombre %></td>
        <td><%= @cliente.direccion %></td>
        <td><%= @cliente.email %></td>
        <td><%= @cliente.telefono %></td>
    </th>           
</div>

<%= link_to "Volver", clientes_path %>

app/views/clientes/index.html.erb
<div>
<% @clientes.each do |item| %>
    <th>
        <td><%= item.id %></td>
        <td><%= item.nombre %></td>
        <td><%= link_to "Detalles", cliente_path(item.id) %></td>
    </th>    
<% end %>
<div>
<%= link_to "Nuevo cliente", new_cliente_path %>        
</div>

<%= link_to "Volver", menu_path %>

app/views/clientes/new.html.erb
<h1>Crear un nuevo cliente</h1>

<%= form_with model: @nuevo do |form| %> 
    <div>
        <%= form.label :nombre %>
        <%= form.text_field :nombre %>
    </div>
    <div>
        <%= form.label :direccion %>
        <%= form.text_field :direccion %>
    </div>
    <div>
        <%= form.label :email %>
        <%= form.text_field :email %>
    </div>
    <div>
        <%= form.label :telefono %>
        <%= form.text_field :telefono %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

<%= link_to "Volver", clientes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Acme&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menu/index.html.erb
<div class="MainPage">
    <%= render "partials/userBar" %>

    <%= link_to "clientes", clientes_path %>

    <%= image_tag(asset_path("ava_logo.png"), alt: "Ava logo", class: "avaLogo") %>
</div>

app/views/partials/_userBar.html.erb
<div class="UserBar">

    <p> Hola <%= @user.nickname %> </p>

    <% if user_signed_in? %>
        <%= button_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
    <% end %>
</div>